Exit build when error, exit with 0 otherwise

diff --git a/travis/build-guide b/travis/build-guide
--- a/travis/build-guide
+++ b/travis/build-guide
@@ -8,32 +8,46 @@ export GUIDE_NAME=${PWD##*/}
 
 if [[ $EXIT_STATUS -eq 0 ]]; then
     ./gradlew publishGuide || EXIT_STATUS=$?
+else
+    echo "Gradle Check failed" 
+    exit $EXIT_STATUS
 fi
 
-if [[ $EXIT_STATUS -eq 0 && $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then
-    echo "Publishing Documentation"
-    git config --global user.name "$GIT_NAME"
-    git config --global user.email "$GIT_EMAIL"
-    git config --global credential.helper "store --file=~/.git-credentials"
-    echo "https://$GH_TOKEN:@github.com" > ~/.git-credentials
+if [[ $EXIT_STATUS -eq 0 ]]; then
+    if [[$TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then
+        echo "Publishing Documentation"
+        git config --global user.name "$GIT_NAME"
+        git config --global user.email "$GIT_EMAIL"
+        git config --global credential.helper "store --file=~/.git-credentials"
+        echo "https://$GH_TOKEN:@github.com" > ~/.git-credentials
 
-    git clone https://${GH_TOKEN}@github.com/grails/grails-guides.git -b gh-pages gh-pages --single-branch > /dev/null
+        git clone https://${GH_TOKEN}@github.com/grails/grails-guides.git -b gh-pages gh-pages --single-branch > /dev/null
     
-    ./gradlew updateGuidesJson
-
-    cd gh-pages
-
+        echo "Updating Guides JSON"
+        ./gradlew updateGuidesJson || EXIT_STATUS=$?
         
-    # If this is the master branch then update the snapshot
-    mkdir -p "$GUIDE_NAME"
-    cp -r ../build/docs/. "./$GUIDE_NAME/"
+        if [[ $EXIT_STATUS -eq 0 ]]; then
 
-    git add .   
+            cd gh-pages
+        
+            # If this is the master branch then update the snapshot
+            mkdir -p "$GUIDE_NAME"
+            cp -r ../build/docs/. "./$GUIDE_NAME/"
 
-    git commit -a -m "Publishing Grails Guide for Travis Build: https://travis-ci.org/$TRAVIS_REPO_SLUG/builds/$TRAVIS_BUILD_ID"
-    git push origin HEAD
-    cd ..
-    rm -rf gh-pages
+            git add .   
+
+            git commit -a -m "Publishing Grails Guide for Travis Build: https://travis-ci.org/$TRAVIS_REPO_SLUG/builds/$TRAVIS_BUILD_ID"
+            git push origin HEAD
+            cd ..
+            rm -rf gh-pages
+            
+        else 
+            echo "Failure updating Guides Json"
+            exit $EXIT_STATUS            
+        fi
+    fi
+else 
+    echo "Gradle Publish Guide failed" 
+    exit $EXIT_STATUS
 fi    
-
-exit $EXIT_STATUS
+exit 0
