Simplify build-guide script

diff --git a/travis/build-guide b/travis/build-guide
--- a/travis/build-guide
+++ b/travis/build-guide
@@ -8,48 +8,45 @@ echo "Publishing guide for branch $TRAVIS_BRANCH"
 
 ./gradlew check || EXIT_STATUS=$?
 
-if [[ $EXIT_STATUS -eq 0 ]]; then
-    ./gradlew publishGuide || EXIT_STATUS=$?
-else
-    echo "Gradle Check failed" 
+if [[ $EXIT_STATUS -ne 0 ]]; then
+    echo "Check failed" 
     exit $EXIT_STATUS
 fi
 
-if [[ $EXIT_STATUS -eq 0 ]]; then
-    if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then
-        echo "Publishing Documentation"
-        git config --global user.name "$GIT_NAME"
-        git config --global user.email "$GIT_EMAIL"
-        git config --global credential.helper "store --file=~/.git-credentials"
-        echo "https://$GH_TOKEN:@github.com" > ~/.git-credentials
-
-        git clone https://${GH_TOKEN}@github.com/grails/grails-guides.git -b gh-pages gh-pages --single-branch > /dev/null
-    
-        echo "Updating Guides JSON"
-        ./gradlew updateGuidesJson || EXIT_STATUS=$?
-        
-        if [[ $EXIT_STATUS -eq 0 ]]; then
-
-            cd gh-pages
-        
-            # If this is the master branch then update the snapshot
-            mkdir -p "$GUIDE_NAME"
-            cp -r ../build/docs/. "./$GUIDE_NAME/"
-
-            git add .   
-
-            git commit -a -m "Publishing Grails Guide for Travis Build: https://travis-ci.org/$TRAVIS_REPO_SLUG/builds/$TRAVIS_BUILD_ID"
-            git push origin HEAD
-            cd ..
-            rm -rf gh-pages
-            
-        else 
-            echo "Failure updating Guides Json"
-            exit $EXIT_STATUS            
-        fi
-    fi
-else 
-    echo "Gradle Publish Guide failed" 
+./gradlew publishGuide || EXIT_STATUS=$?
+if [[ $EXIT_STATUS -ne 0 ]]; then
+    echo "PublishGuide failed" 
     exit $EXIT_STATUS
+fi  
+
+if [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
+    echo "Publishing Documentation"
+    git config --global user.name "$GIT_NAME"
+    git config --global user.email "$GIT_EMAIL"
+    git config --global credential.helper "store --file=~/.git-credentials"
+    echo "https://$GH_TOKEN:@github.com" > ~/.git-credentials
+
+    git clone https://${GH_TOKEN}@github.com/grails/grails-guides.git -b gh-pages gh-pages --single-branch > /dev/null
+    
+    echo "Updating Guides JSON"
+    ./gradlew updateGuidesJson || EXIT_STATUS=$?
+    if [[ $EXIT_STATUS -ne 0 ]]; then
+        echo "updateGuidesJson failed" 
+        rm -rf gh-pages
+        exit $EXIT_STATUS    
+    fi
+    
+    cd gh-pages
+
+    # If this is the master branch then update the snapshot
+    mkdir -p "$GUIDE_NAME"
+    cp -r ../build/docs/. "./$GUIDE_NAME/"
+
+    git add .   
+
+    git commit -a -m "Publishing Grails Guide for Travis Build: https://travis-ci.org/$TRAVIS_REPO_SLUG/builds/$TRAVIS_BUILD_ID"
+    git push origin HEAD
+    cd ..
+    rm -rf gh-pages
 fi    
 exit 0
