Update build-guide to skip tests

diff --git a/githubactions/build-guide b/githubactions/build-guide
--- a/githubactions/build-guide
+++ b/githubactions/build-guide
@@ -6,12 +6,12 @@ export GUIDE_NAME=${PWD##*/}
 
 echo "Publishing guide for branch $GITHUB_REF"
 
-./gradlew -Dgeb.env=chromeHeadless check || EXIT_STATUS=$?
+#./gradlew -Dgeb.env=chromeHeadless check || EXIT_STATUS=$?
 
-if [[ $EXIT_STATUS -ne 0 ]]; then
-    echo "Check failed" 
-    exit $EXIT_STATUS
-fi
+#if [[ $EXIT_STATUS -ne 0 ]]; then
+#    echo "Check failed" 
+#    exit $EXIT_STATUS
+#fi
 
 ./gradlew publishGuide || EXIT_STATUS=$?
 if [[ $EXIT_STATUS -ne 0 ]]; then
